# Generated by Django 5.2.7 on 2026-07-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DekaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='AthleteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('age_group', models.CharField(blank=True, max_length=64)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('run_length_1', models.DurationField(blank=True, null=True)),
                ('run_length_2', models.DurationField(blank=True, null=True)),
                ('run_length_3', models.DurationField(blank=True, null=True)),
                ('run_length_4', models.DurationField(blank=True, null=True)),
                ('run_length_5', models.DurationField(blank=True, null=True)),
                ('run_length_6', models.DurationField(blank=True, null=True)),
                ('run_length_7', models.DurationField(blank=True, null=True)),
                ('run_length_8', models.DurationField(blank=True, null=True)),
                ('run_length_9', models.DurationField(blank=True, null=True)),
                ('run_length_10', models.DurationField(blank=True, null=True)),
                ('exercise_1', models.DurationField(blank=True, null=True)),
                ('exercise_2', models.DurationField(blank=True, null=True)),
                ('exercise_3', models.DurationField(blank=True, null=True)),
                ('exercise_4', models.DurationField(blank=True, null=True)),
                ('exercise_5', models.DurationField(blank=True, null=True)),
                ('exercise_6', models.DurationField(blank=True, null=True)),
                ('exercise_7', models.DurationField(blank=True, null=True)),
                ('exercise_8', models.DurationField(blank=True, null=True)),
                ('exercise_9', models.DurationField(blank=True, null=True)),
                ('exercise_10', models.DurationField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.dekaevent')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['event', 'gender', 'category', 'age_group', 'athlete_name', 'total_time'],
                'constraints': [models.UniqueConstraint(fields=('event', 'athlete_name', 'category', 'gender', 'age_group'), name='unique_result_per_athlete_per_event')],
            },
        ),
    ]
