# Generated by Django 5.2.7 on 2026-07-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_1',
            new_name='run_1',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_10',
            new_name='run_10',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_2',
            new_name='run_2',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_3',
            new_name='run_3',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_4',
            new_name='run_4',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_5',
            new_name='run_5',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_6',
            new_name='run_6',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_7',
            new_name='run_7',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_8',
            new_name='run_8',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='run_length_9',
            new_name='run_9',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_1',
            new_name='zone_1',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_10',
            new_name='zone_10',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_2',
            new_name='zone_2',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_3',
            new_name='zone_3',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_4',
            new_name='zone_4',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_5',
            new_name='zone_5',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_6',
            new_name='zone_6',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_7',
            new_name='zone_7',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_8',
            new_name='zone_8',
        ),
        migrations.RenameField(
            model_name='athleteresult',
            old_name='exercise_9',
            new_name='zone_9',
        ),
    ]
