# Generated by Django 5.2.7 on 2026-07-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_athleteresult_unique_result_per_athlete_per_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteresult',
            name='age_group',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='athleteresult',
            name='gender',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
