# Generated by Django 5.2.7 on 2026-07-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DekaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='AthleteResult',
            fields=[
                ('athlete_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('deka_type', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('age_group', models.CharField(blank=True, max_length=64)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('run_1', models.DurationField(blank=True, null=True)),
                ('run_2', models.DurationField(blank=True, null=True)),
                ('run_3', models.DurationField(blank=True, null=True)),
                ('run_4', models.DurationField(blank=True, null=True)),
                ('run_5', models.DurationField(blank=True, null=True)),
                ('run_6', models.DurationField(blank=True, null=True)),
                ('run_7', models.DurationField(blank=True, null=True)),
                ('run_8', models.DurationField(blank=True, null=True)),
                ('run_9', models.DurationField(blank=True, null=True)),
                ('run_10', models.DurationField(blank=True, null=True)),
                ('zone_1', models.DurationField(blank=True, null=True)),
                ('zone_2', models.DurationField(blank=True, null=True)),
                ('zone_3', models.DurationField(blank=True, null=True)),
                ('zone_4', models.DurationField(blank=True, null=True)),
                ('zone_5', models.DurationField(blank=True, null=True)),
                ('zone_6', models.DurationField(blank=True, null=True)),
                ('zone_7', models.DurationField(blank=True, null=True)),
                ('zone_8', models.DurationField(blank=True, null=True)),
                ('zone_9', models.DurationField(blank=True, null=True)),
                ('zone_10', models.DurationField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.dekaevent')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['event', 'deka_type', 'gender', 'category', 'age_group', 'athlete_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'athlete_name', 'deka_type', 'category'), name='unique_result_per_athlete_per_event')],
            },
        ),
    ]
