# Generated by Django 6.0.7 on 2026-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_athleteresult_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dekaevent',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dekaevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dekaevent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dekaevent',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
