# Generated by Django 6.0.7 on 2026-08-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'RaceInfo',
                'verbose_name_plural': 'RaceInfos',
            },
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.raceinfo')),
            ],
            options={
                'verbose_name': 'EventInfo',
                'verbose_name_plural': 'EventInfos',
            },
        ),
        migrations.CreateModel(
            name='AthleteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('age_group', models.CharField(blank=True, max_length=64, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('run_1', models.DurationField(blank=True, null=True)),
                ('run_2', models.DurationField(blank=True, null=True)),
                ('run_3', models.DurationField(blank=True, null=True)),
                ('run_4', models.DurationField(blank=True, null=True)),
                ('run_5', models.DurationField(blank=True, null=True)),
                ('run_6', models.DurationField(blank=True, null=True)),
                ('run_7', models.DurationField(blank=True, null=True)),
                ('run_8', models.DurationField(blank=True, null=True)),
                ('run_9', models.DurationField(blank=True, null=True)),
                ('run_10', models.DurationField(blank=True, null=True)),
                ('zone_1', models.DurationField(blank=True, null=True)),
                ('zone_2', models.DurationField(blank=True, null=True)),
                ('zone_3', models.DurationField(blank=True, null=True)),
                ('zone_4', models.DurationField(blank=True, null=True)),
                ('zone_5', models.DurationField(blank=True, null=True)),
                ('zone_6', models.DurationField(blank=True, null=True)),
                ('zone_7', models.DurationField(blank=True, null=True)),
                ('zone_8', models.DurationField(blank=True, null=True)),
                ('zone_9', models.DurationField(blank=True, null=True)),
                ('zone_10', models.DurationField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.eventinfo')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['event', 'gender', 'category', 'age_group', 'total_time', 'athlete_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'athlete_name', 'category'), name='unique_result_per_athlete_per_event')],
            },
        ),
    ]
