# Generated by Django 6.0.7 on 2026-08-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceinfo',
            name='zone_1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_10',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_3',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_4',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_5',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_6',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_7',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_8',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceinfo',
            name='zone_9',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
